function scs_database = scs_database_creator(cellTypes, responsePatterns)
% creates a database -- an array of structures containing detailed analysis
% of cell responses recorded during calcium imaging across many
% experiments.
% INPUTS:
%                       cellTypeOfInterests; type(s) of cells present in a
%                               new dataBase -- cell array
%                       responsePattern; the pattern(s) of
%                               cells present in the new dataBase Please
%                               see scsIdentifier for pattern to
%                               classification conversion. -- cell array
% OUTPUTS:              dataBaseStruct; an array of structs containing
%                               database entries, with fields:
%                                   date, recordingLocation,
%                                   recordingDepth, cellID, cellType,
%                                   classification, maxAreaAngle, nSigma,
%                                   maxSurroundAngle
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%% GET ANALYZED IMEXPS %%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Call the multiexp loader to load analyzed imaging experiments load only
% the cell types and classification fields
[loadedImExps, imExpNames] = multiImExpLoader('analyzed', 'all');
                            
for exp = 1:numel(imExpNames)
    imExp = loadedImExps{exp};
    
    % Construct Name for exp to add to database
    fullName = imExpNames{exp};
    [C, ~] = strsplit(fullName,'_');
    imExpName = [C{2},'_',strrep(C{1},'-','_')];
    
    for roiSet = 1:numel(imExp.rois)
        for roiNum = 1:numel(imExp.rois{roiSet})
            % make sure there is an roi 
            if ~isempty(imExp.rois{roiSet}{roiNum})
                % get the cell type and the classification for this roi
                type = imExp.cellTypes{roiSet}{roiNum};
                % get the classification of this cell
                classif = ...
                 imExp.signalClassification.classification{roiSet}{roiNum};
             
                % see if the response matches the user selected
                % classifications they want for this particular cell type
                switch type
                    
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                    %%%%%%%%%%%%%%%%%%%%%% CELL TYPE 1 %%%%%%%%%%%%%%%%%%%%
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                    
                    case cellTypes{1}
                        % Get the response see identifyScsPattern
                        response = identifyScsPattern(cellTypes{1},...
                                                      classif);
                                                  
                        if ismember(response, responsePatterns{1})
                            
                            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                            %%%%%%%%%% ADD IMEXP STRUCTURES %%%%%%%%%%%%%%%
                            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                            
                            %%%%%%%%%%%%%%% File Info %%%%%%%%%%%%%%%%%%%%%
                            scs_database.(cellTypes{1}).(imExpName)...
                                .fileInfo = imExp.fileInfo;
                            
                            %%%%%%%%%%%%% Encoder Options %%%%%%%%%%%%%%%%%
                            scs_database.(cellTypes{1}).(imExpName)...
                                .encoderOptions = imExp.encoderOptions;
                            
                            %%%%%%%%%%%%%%%% Stimulus %%%%%%%%%%%%%%%%%%%%%
                            scs_database.(cellTypes{1}).(imExpName)...
                                .stimulus = imExp.stimulus;
                            
                            %%%%%%%%%%%%%%% Behavior %%%%%%%%%%%%%%%%%%%%%%
                            scs_database.(cellTypes{1}).(imExpName)...
                                .behavior = imExp.behavior;
                            
                            %%%%%%%%%%%%%%%%%% Rois %%%%%%%%%%%%%%%%%%%%%%% 
                            scs_database.(cellTypes{1}).(imExpName)...
                                .rois = imExp.rois;
                           
                            %%%%%%%%%%%%%%%%%% SignalRunState %%%%%%%%%%%%%
                            scs_database.(cellTypes{1}).(imExpName)...
                                .signalRunState = imExp.SignalRunState;
             
                            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                            %%%%%%%%%%%%%%%% ANALYZED DATA %%%%%%%%%%%%%%%%
                            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                            
                            %%%%%%%%%%%%% Signal Maps %%%%%%%%%%%%%%%%%%%%%
                            scs_database.(cellTypes{1}).(imExpName)...
                                .signalMaps{roiSet,roiNum} =...
                                imExp.signalMaps{roiSet}{roiNum};
                            
                            %%%%%%%%%%%%% Area metrics %%%%%%%%%%%%%%%%%%%%
                            scs_database.(cellTypes{1}).(imExpName)...
                                .areaMetrics.meanAreas{roiSet,...
                                roiNum} = imExp.areaMetrics...
                                .meanAreas{roiSet}{roiNum};
                            
                            scs_database.(cellTypes{1}).(imExpName)...
                                .areaMetrics.stdAreas{roiSet,...
                                roiNum} = imExp.areaMetrics...
                                .stdAreas{roiSet}{roiNum};
                            
                            %%%%%%%%%%%%% signal classification %%%%%%%%%%%
                            scs_database.(cellTypes{1}).(imExpName)...
                                .signalClassification.classification{...
                                roiSet,roiNum} = ...
                                imExp.signalClassification...
                                .classification{roiSet}{roiNum};
                            
                            scs_database.(cellTypes{1}).(imExpName)...
                                .signalClassification.maxAreaAngle{...
                                roiSet,roiNum} = ...
                                imExp.signalClassification...
                                .maxAreaAngle{roiSet}{roiNum};
                            
                            scs_database.(cellTypes{1}).(imExpName)...
                                .signalClassification.maxSurroundAngle{...
                                roiSet,roiNum} = ...
                                imExp.signalClassification...
                                .maxSurroundAngle{roiSet}{roiNum};
                            
                            scs_database.(cellTypes{1}).(imExpName)...
                                .signalClassification.nSigma{...
                                roiSet,roiNum} = ...
                                imExp.signalClassification...
                                .classification{roiSet}{roiNum};
                            
                            %%%%%%%%%%%%%% signalMetrics %%%%%%%%%%%%%%%%%%
                            scs_database.(cellTypes{1}).(imExpName)...
                                .signalMetrics.surroundGains{roiSet,...
                                roiNum} = imExp.signalMetrics...
                                .surroundGains{roiSet}{roiNum};
                            
                            scs_database.(cellTypes{1}).(imExpName)...
                                .signalMetrics.suppressionIndex{roiSet,...
                                roiNum} = imExp.signalMetrics...
                                .suppressionIndex{roiSet}{roiNum};
                            
                            scs_database.(cellTypes{1}).(imExpName)...
                                .signalMetrics.surroundOriIndex{roiSet,...
                                roiNum} = imExp.signalMetrics...
                                .surroundOriIndex{roiSet}{roiNum};
                        
                        end % Ends ismember of responses
                    
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                    %%%%%%%%%%%%%%%%%%%%%% CELL TYPE 2 %%%%%%%%%%%%%%%%%%%%
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                    
                    case cellTypes{2}
                        % Get the response see identifyScsPattern
                        response = identifyScsPattern(cellTypes{2},...
                                                      classif);
                                                  
                        if ismember(response, responsePatterns{2})
                            
                            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                            %%%%%%%%%% ADD IMEXP STRUCTURES %%%%%%%%%%%%%%%
                            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                            
                            %%%%%%%%%%%%%%% File Info %%%%%%%%%%%%%%%%%%%%%
                            scs_database.(cellTypes{2}).(imExpName)...
                                .fileInfo = imExp.fileInfo;
                            
                            %%%%%%%%%%%%% Encoder Options %%%%%%%%%%%%%%%%%
                            scs_database.(cellTypes{2}).(imExpName)...
                                .encoderOptions = imExp.encoderOptions;
                            
                            %%%%%%%%%%%%%%%% Stimulus %%%%%%%%%%%%%%%%%%%%%
                            scs_database.(cellTypes{2}).(imExpName)...
                                .stimulus = imExp.stimulus;
                            
                            %%%%%%%%%%%%%%% Behavior %%%%%%%%%%%%%%%%%%%%%%
                            scs_database.(cellTypes{2}).(imExpName)...
                                .behavior = imExp.behavior;
                            
                            %%%%%%%%%%%%%%%%%% Rois %%%%%%%%%%%%%%%%%%%%%%% 
                            scs_database.(cellTypes{2}).(imExpName)...
                                .rois = imExp.rois;
                           
                            %%%%%%%%%%%%%%%%%% SignalRunState %%%%%%%%%%%%%
                            scs_database.(cellTypes{2}).(imExpName)...
                                .signalRunState = imExp.SignalRunState;
             
                            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                            %%%%%%%%%%%%%%%% ANALYZED DATA %%%%%%%%%%%%%%%%
                            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                            
                            %%%%%%%%%%%%% Signal Maps %%%%%%%%%%%%%%%%%%%%%
                            scs_database.(cellTypes{2}).(imExpName)...
                                .signalMaps{roiSet,roiNum} =...
                                imExp.signalMaps{roiSet}{roiNum};
                            
                            %%%%%%%%%%%%% Area metrics %%%%%%%%%%%%%%%%%%%%
                            scs_database.(cellTypes{2}).(imExpName)...
                                .areaMetrics.meanAreas{roiSet,...
                                roiNum} = imExp.areaMetrics...
                                .meanAreas{roiSet}{roiNum};
                            
                            scs_database.(cellTypes{2}).(imExpName)...
                                .areaMetrics.stdAreas{roiSet,...
                                roiNum} = imExp.areaMetrics...
                                .stdAreas{roiSet}{roiNum};
                            
                            %%%%%%%%%%%%% signal classification %%%%%%%%%%%
                            scs_database.(cellTypes{2}).(imExpName)...
                                .signalClassification.classification{...
                                roiSet,roiNum} = ...
                                imExp.signalClassification...
                                .classification{roiSet}{roiNum};
                            
                            scs_database.(cellTypes{2}).(imExpName)...
                                .signalClassification.maxAreaAngle{...
                                roiSet,roiNum} = ...
                                imExp.signalClassification...
                                .maxAreaAngle{roiSet}{roiNum};
                            
                            scs_database.(cellTypes{2}).(imExpName)...
                                .signalClassification.maxSurroundAngle{...
                                roiSet,roiNum} = ...
                                imExp.signalClassification...
                                .maxSurroundAngle{roiSet}{roiNum};
                            
                            scs_database.(cellTypes{2}).(imExpName)...
                                .signalClassification.nSigma{...
                                roiSet,roiNum} = ...
                                imExp.signalClassification...
                                .classification{roiSet}{roiNum};
                            
                            %%%%%%%%%%%%%% signalMetrics %%%%%%%%%%%%%%%%%%
                            scs_database.(cellTypes{2}).(imExpName)...
                                .signalMetrics.surroundGains{roiSet,...
                                roiNum} = imExp.signalMetrics...
                                .surroundGains{roiSet}{roiNum};
                            
                            scs_database.(cellTypes{2}).(imExpName)...
                                .signalMetrics.suppressionIndex{roiSet,...
                                roiNum} = imExp.signalMetrics...
                                .suppressionIndex{roiSet}{roiNum};
                            
                            scs_database.(cellTypes{2}).(imExpName)...
                                .signalMetrics.surroundOriIndex{roiSet,...
                                roiNum} = imExp.signalMetrics...
                                .surroundOriIndex{roiSet}{roiNum};
                        
                        end % Ends ismember of responses
                        
                end % ends swith cellType
            end
        end
    end
end

                                
    
    



end

